### ISSUE TITLE
It dosen't work

### ISSUE THREAD

**Issue by yangwcool** [pluveto/flydav#19]
still need to enter username and password, even though I have specified a username at startup. 
What does the `Password(Encrypted)` in console mean? no useful info found in readme.

```
flydav.exe -u user1 -c config.yaml
```

```yaml
server:
  host: 0.0.0.0
  port: 5000
  path: /webdav
  fs_dir: E:/foo/bar
log:
  level: Warning
```
